### ISSUE TITLE
Dynamic import causes Rollup error.

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/svelte.dev#503]
```svelte
{#await import('./Component.svelte') then { default: Counter }}
  <Counter />
{/await}
```
[Playground](https://svelte-omnisite.vercel.app/playground/0741bd662ebf432fa487fd5e676102b9?version=5.0.5#H4sIAAAAAAAACnVPy07DMBD8ldWC1ESNGno1SSTUE9-AObhmq0RN1la84SHL_46SgKCoHGd2ZnYm4qnrKaB6iigfnlAtBBbIZpjRg_e78Eq9zNzRBLrGW8dCLAEVxhvzZjqBbvBulGyzKw9u8I6J5Uu_yUFaYojwQicz9aLg4CYWGiElzQDVNywbzbFc8pJmLFDoXVDJOFEq_un799tl6yvXX92rYMfOS6NZS08Cdu4BNdwGMULZXX6vuSp_RFwdJxHH4Nj2nT3XMcuhblbfdpuWoEe2Iw3EMntX_ept980yVEFcDKkq231zufI5fQL9XE1voQEAAA==)

```
RollupError: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
    at Ji (index-DDKZTKvH.js:25:919)
    at F (index-DDKZTKvH.js:25:870)
    at index-DDKZTKvH.js:56:1241
    at Wp.generate (index-DDKZTKvH.js:56:1864)
    at async index-DDKZTKvH.js:57:45862
    at async sg (index-DDKZTKvH.js:112:163)
    at async index-DDKZTKvH.js:80:185
```

**Comment by teemingc** [comment]
Can't reproduce on https://svelte.dev/playground/47c19aa3a9e7497b858ac1c57a39fb68?version=5.53.3
