### ISSUE TITLE
Playground editor throws an error if .svelte.js file is added - Uncaught TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Leonidaz** [sveltejs/svelte.dev#705]
Steps to replicate:

- Go to the playground [playground](https://svelte.dev/playground/hello-world?version=5.1.4#H4sIAAAAAAAAE3WOyw6CMBBFf6XOBk0IhG0pJO78B-sCYZSaMhA6vkL4d1MfURLcnpybewagokGQsEFrW3Fte1uJJVaGsVpBCAdj0YHcDsD3znseQPhZrbsuche07Nm-cDjHy5YYiR1IUK7sTce5Js0WWXhdZCJ4_gapJhV_DVJ1kr-6Bi-OCxXXSa4JQmC8MUjuzziGf9pc2yDXho7vkujkppHzwk-tJt_I6FhkIkmnt7vxAQA4ZHg8AQAA)
- switch the file tab to `something.svelte.js`
- console now has an error:
```
Editor.CTcXyXIj.js:426 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Editor.CTcXyXIj.js:426:6763
    at jt (runtime.KO4QJO6K.js:1:8130)
    at St (runtime.KO4QJO6K.js:1:3713)
    at Rt (runtime.KO4QJO6K.js:1:3762)
    at M (runtime.KO4QJO6K.js:1:7804)
    at In (runtime.KO4QJO6K.js:1:9187)
    at Ut (runtime.KO4QJO6K.js:1:9081)
    at Sn (runtime.KO4QJO6K.js:1:9341)
```
- typing anything in the file causes this error

**Comment by teemingc** [comment]
Can't reproduce
